import type { Listing } from "@/lib/idx/types";

export const mockListings: Listing[] = [
  {
    id: "listing-1",
    slug: "713-main-street-windermere-fl-34786",
    price: 2285000,
    beds: 5,
    baths: 5,
    sqft: 4580,
    address: "713 Main Street",
    city: "Windermere",
    state: "FL",
    zip: "34786",
    image: "/images/properties/main-street-windermere.jpg",
    status: "active",
    description:
      "Exclusive Windermere estate in the heart of downtown. This stunning property offers refined living with curated interiors, expansive terraces, and luxury finishes throughout.",
    features: ["Downtown Location", "Chef's Kitchen", "Pool", "Smart Home"],
    latitude: 28.495,
    longitude: -81.535
  },
  {
    id: "listing-2",
    slug: "18725-south-obrien-road-groveland-fl-34736",
    price: 1265000,
    beds: 5,
    baths: 4,
    sqft: 3850,
    address: "18725 South Obrien Road",
    city: "Groveland",
    state: "FL",
    zip: "34736",
    image: "/images/properties/obrien-road.jpg",
    status: "active",
    description: "Magnificent luxury estate on expansive acreage offering privacy and resort-style amenities. Perfect for those seeking space and sophistication.",
    features: ["Acreage", "Private Setting", "Pool & Spa", "Guest Suite"],
    latitude: 28.521,
    longitude: -81.851
  },
  {
    id: "listing-3",
    slug: "1004-vinsetta-circle-winter-garden-fl-34787",
    price: 918000,
    beds: 5,
    baths: 4,
    sqft: 3420,
    address: "1004 Vinsetta Circle",
    city: "Winter Garden",
    state: "FL",
    zip: "34787",
    image: "/images/properties/vinsetta-circle.jpg",
    status: "active",
    description: "Elegant Winter Garden home in a prestigious community. Features open floor plan, gourmet kitchen, and resort-style backyard with pool.",
    features: ["Gated Community", "Pool", "Open Floor Plan", "3-Car Garage"],
    latitude: 28.565,
    longitude: -81.586
  },
  {
    id: "listing-4",
    slug: "8158-emerald-forest-court-sanford-fl-32771",
    price: 795000,
    beds: 4,
    baths: 3,
    sqft: 2980,
    address: "8158 Emerald Forest Court",
    city: "Sanford",
    state: "FL",
    zip: "32771",
    image: "/images/properties/emerald-forest.jpg",
    status: "active",
    description: "Beautiful Sanford home nestled in a private, wooded setting. Modern amenities meet natural beauty in this stunning property.",
    features: ["Wooded Lot", "Updated Kitchen", "Screened Pool", "Conservation View"],
    latitude: 28.801,
    longitude: -81.273
  },
  {
    id: "listing-5",
    slug: "8869-rhodes-street-kissimmee-fl-34747",
    price: 610000,
    beds: 6,
    baths: 5,
    sqft: 3142,
    address: "8869 Rhodes Street",
    city: "Kissimmee",
    state: "FL",
    zip: "34747",
    image: "/images/properties/rhodes-street.jpg",
    status: "active",
    description: "Explore the potential of this beautifully designed, investment-ready home in the sought-after Windsor Island Resort. This luxurious 6-bedroom, 5-bathroom home with private pool and hot tub is designed to impress. Located just 20 minutes from Disney World.",
    features: ["Resort Community", "Private Pool", "Hot Tub", "Near Disney"],
    latitude: 28.289,
    longitude: -81.589
  },
  {
    id: "listing-6",
    slug: "2609-slagrove-court-winter-garden-fl-34787",
    price: 555000,
    beds: 4,
    baths: 2,
    sqft: 2383,
    address: "2609 Slagrove Court",
    city: "Winter Garden",
    state: "FL",
    zip: "34787",
    image: "/images/properties/slagrove-court.jpg",
    status: "active",
    description: "Welcome to Stoneybrook West, a gated golf community in the heart of Winter Garden. This single-story home sits on an oversized cul-de-sac lot with 2,383 square feet of living space featuring a 4-bedroom, 2-bath split floor plan. Move-in ready with updated appliances.",
    features: ["Gated Golf Community", "Single Story", "Cul-de-sac Lot", "Updated Appliances"],
    latitude: 28.541,
    longitude: -81.603
  }
];
